### ISSUE TITLE
Vegacapsule panic for vega_visor_mixed.hcl

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vegacapsule#293]
# Command used to start network

```bash
 vegacapsule network bootstrap --config-path ./net_confs/config_visor_mixed.hcl --force
```

# Config file

https://github.com/vegaprotocol/vegacapsule/blob/main/net_confs/config_visor_mixed.hcl

# Issue

```
...
...

2022/10/19 06:12:58 tendermint wallet out: &vega.importNodeWalletOutput{RegistryFilePath:"/Users/daniel/.vegacapsule/testnet/vega/node1/config/node/wallets.encrypted", TendermintPubkey:"tN4WPE+LLydvNEKEskInT4wGQcqvdGII6xPICNRzoE8=", WalletFilePath:""}
2022/10/19 06:12:58 vega config initialized for node "validator" with id 1, paths: "/Users/daniel/.vegacapsule/testnet/vega/node1/config/node/config.toml"
2022/10/19 06:12:58 Overwriting Tendermint config for nodeset testnet-nodeset-validators-0-validator
2022/10/19 06:12:58 Overwriting Vega config for nodeset testnet-nodeset-validators-0-validator
2022/10/19 06:12:58 Overwriting Tendermint config for nodeset testnet-nodeset-validators-1-validator
2022/10/19 06:12:58 Overwriting Vega config for nodeset testnet-nodeset-validators-1-validator
2022/10/19 06:12:58 Overwriting Tendermint config for nodeset testnet-nodeset-full-2-full
2022/10/19 06:12:58 Overwriting Vega config for nodeset testnet-nodeset-full-2-full
2022/10/19 06:12:58 Overwriting Data Node config for nodeset testnet-nodeset-full-2-full
2022/10/19 06:12:58 Overwriting Tendermint config for nodeset testnet-nodeset-visor-3-validator
2022/10/19 06:12:58 Overwriting Vega config for nodeset testnet-nodeset-visor-3-validator
2022/10/19 06:12:58 Overwriting Data Node config for nodeset testnet-nodeset-visor-3-validator
2022/10/19 06:12:58 Overwriting Visor config for nodeset testnet-nodeset-visor-3-validator
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x440552c]

goroutine 1 [running]:
text/template.errRecover(0xc0002f8300)
        /usr/local/go/src/text/template/exec.go:164 +0x165
panic({0x52b07c0, 0x654c7e0})
        /usr/local/go/src/runtime/panic.go:884 +0x212
text/template.(*Template).execute(0x0, {0x5969e00?, 0xc00117d650?}, {0x52f5020?, 0xc00107a9a0?})
        /usr/local/go/src/text/template/exec.go:215 +0x22c
text/template.(*Template).Execute(...)
        /usr/local/go/src/text/template/exec.go:201
code.vegaprotocol.io/vegacapsule/generator/visor.Generator.TemplateConfig({_, {_, _}}, {{0xc000f93048, 0x5}, {0xc001442150, 0x21}, {0xc000f93060, 0x9}, 0x3, ...}, ...)
        /Users/daniel/www/vega/vegacapsule/generator/visor/templates.go:38 +0x127
code.vegaprotocol.io/vegacapsule/generator/visor.Generator.OverwriteConfig({_, {_, _}}, {{0xc000f93048, 0x5}, {0xc001442150, 0x21}, {0xc000f93060, 0x9}, 0x3, ...}, ...)
        /Users/daniel/www/vega/vegacapsule/generator/visor/templates.go:86 +0x7b
code.vegaprotocol.io/vegacapsule/generator/visor.Generator.OverwriteConfigs({_, {_, _}}, {{0xc000f93048, 0x5}, {0xc001442150, 0x21}, {0xc000f93060, 0x9}, 0x3, ...}, ...)
        /Users/daniel/www/vega/vegacapsule/generator/visor/templates.go:74 +0x9b
code.vegaprotocol.io/vegacapsule/generator.(*configOverride).Overwrite(_, {{0xc00038fd8a, 0x5}, {0xc000046b20, 0x9}, 0x2, 0x0, 0x0, 0x0, {0xc0001370c8, ...}, ...}, ...)
        /Users/daniel/www/vega/vegacapsule/generator/config_overwrite.go:99 +0x42c
code.vegaprotocol.io/vegacapsule/generator.(*Generator).configureNodeSets(0xc0012140f0, 0xc0003e82a0, 0x4?)
        /Users/daniel/www/vega/vegacapsule/generator/generator.go:106 +0x388
code.vegaprotocol.io/vegacapsule/generator.(*Generator).Generate(0xc0012140f0)
        /Users/daniel/www/vega/vegacapsule/generator/generator.go:141 +0x132
code.vegaprotocol.io/vegacapsule/cmd.netGenerate({0xc00012e5a0, 0x0, 0x0}, 0x1)
        /Users/daniel/www/vega/vegacapsule/cmd/network_generate.go:91 +0x47e
code.vegaprotocol.io/vegacapsule/cmd.glob..func9(0x6563300, {0x54ac15f?, 0x3?, 0x3?})
        /Users/daniel/www/vega/vegacapsule/cmd/network_bootstrap.go:50 +0x570
github.com/spf13/cobra.(*Command).execute(0x6563300, {0xc000302e40, 0x3, 0x3})
        /Users/daniel/www/vega/vegacapsule/vendor/github.com/spf13/cobra/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x6566000)
        /Users/daniel/www/vega/vegacapsule/vendor/github.com/spf13/cobra/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/daniel/www/vega/vegacapsule/vendor/github.com/spf13/cobra/command.go:918
code.vegaprotocol.io/vegacapsule/cmd.Execute(...)
        /Users/daniel/www/vega/vegacapsule/cmd/root.go:21
main.main()
        /Users/daniel/www/vega/vegacapsule/main.go:10 +0x25
```

**Comment by daniel1302** [comment]
Here is fix(WORKAROUND) for panic: https://github.com/vegaprotocol/vegacapsule/pull/265/files

But this is not proper fix. Vegacapsule must check if there is missing field in config and return the proper error

**Comment by fkondej** [comment]
closing as old one
